version: '3.2'

services:

  app:
    image: ghcr.io/mamura/php81-fpm:latest
    labels:
      - traefik.http.routers.gandauth.rule=Host(`gandauth.mamura.test`)
      #- traefik.http.services.gandauth.loadbalancer.server.port=5173
    volumes:
      - ./src:/src
    environment:
      - PROJECT_WEBROOT=/src/public
    ports:
      - '5173:5173'

networks:
  default:
      name: dev-network